from snakemake.utils import min_version

# set minimum snakemake version
min_version("6.4.1")

# setup config file
configfile: "config/config.yaml"

# load rules
include: "rules/gather.smk"


# all rule 
rule all:
    input: "results/events.txt"