# Conda environment for reducing fermi data
name: snakemake-workflow-fermi-lat

channels:
  - conda-forge
  - bioconda
  - fermi

variables:
  PYTHONNOUSERSITE: "1"

dependencies:
  - python=3.9
  - snakemake>=6.4.1
  - pydantic==1.10.13
  - scipy==1.11.3
  - astropy==5.3.4
  - gammapy==1.1
  - fermitools>=2.2.0
