# Conda environment for reducing fermi data
name: snakemake-workflow-fermi-lat

channels:
  - conda-forge
  - bioconda
  - fermi

variables:
  PYTHONNOUSERSITE: "1"

dependencies:
  - python=3.9
  - snakemake>=6.4.1
  - pydantic<2.0
  - scipy<1.12
  - astropy>=5.2
  - gammapy>=1.0
  - fermitools>=2.2.0
