name: my-config
scfile: data/L230210105554348FF7BE69_SC00.fits
event_types: ["psf0", "psf1", "psf2", "psf3"]
fermitools:
  gtselect:
    ra: &ra "08h52m00s"
    dec: &dec "-46d19m58.80065918s"
    rad: 3 deg
    tmin: &tmin "2008-08-04 15:43:36"
    tmax: &tmax "2023-02-10 21:46:14"
    emin: &emin 10 GeV
    emax: &emax 2 TeV
    zmax: &zmax 105 deg
    evclass: 128
  gtmktime:
    filter: "'(DATA_QUAL>0)&&(LAT_CONFIG==1)'"
    roicut: "yes"
  gtbin:
    algorithm: CCUBE
    nxpix: &nxpix 200
    nypix: &nypix 200
    binsz: &binsz 0.02
    xref: &xref 266.25888553
    yref: &yref -1.21964555
    proj: &proj CAR
    coordsys: &coordsys GAL
    ebinalg: &ebinalg LOG
    enumbins: 11
    axisrot: &axisrot 0
    emin: *emin
    emax: *emax
  gtltcube:
    dcostheta: 0.025
    binsz: 1.
    tmin: *tmin
    tmax: *tmax
    zmax: *zmax
  gtexpcube2:
    coordsys: *coordsys
    binsz: *binsz
    nxpix: *nxpix
    nypix: *nypix
    xref: *xref
    yref: *yref
    proj: *proj
    ebinalg: *ebinalg
    cmap: none
    emin: &emin_true 5 GeV
    emax: &emax_true 2 TeV
    enumbins: 16
    axisrot: *axisrot
    bincalc: EDGE
  gtpsf:
    thetamax: 10
    ntheta: 300
    ra: *ra
    dec: *dec
    emin: *emin_true
    emax: *emax_true
    nenergies: 17


